spring:
  config:
    activate:
      on-profile: dev

#  shell:
#    interactive:
#      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/driver
    username: postgres
    password: ibraxim
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: off

    properties:
      hibernate:
        format_sql: true


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false



application:
    jwt:
      access-token-expire: 300000
      refresh-token-expire: 600000
      secret: bu_secret_kalit_hech_kim_bilmasin_oka_78_hop



logging:
  level:
    root: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: WARN

app:
  sync-db: true



